<?php
/** @var \ParadoxLabs\Authnetcim\Block\Customer\Form\Cc $block */
/** @var \Magento\Framework\Escaper $escaper */

use Magento\Customer\Helper\Address;
use Magento\Directory\Helper\Data;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

?>
<?php $code = $escaper->escapeHtmlAttr($block->getCode()); ?>

<div class="block-title">
    <h2>
        <?php if ($block->isEdit()): ?>
            <?= $escaper->escapeHtml(__('Editing %1', $block->getCard()->getLabel())); ?>
        <?php else: ?>
            <?= $escaper->escapeHtml(__($block->getData('default_title'))); ?>
        <?php endif; ?>
    </h2>
</div>

<form action="<?= $escaper->escapeHtmlAttr($block->getAction() . '?method=' . $code); ?>" method="post" id="form-validate" class="checkout-payment-method" data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <input type="hidden" name="id" value="<?= $block->getCard()->getId() ? $escaper->escapeHtmlAttr($block->getCard()->getHash()) : ''; ?>" />
    <input type="hidden" name="source" value="paymentinfo" />
    <fieldset class="fieldset address">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Cardholder Information')) ?></span></legend><br>

        <?= /* @noEscape */ $block->getNameBlockHtml() ?>
        <div class="field company">
            <label class="label" for="company"><span><?= $escaper->escapeHtml(__('Company')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[company]" id="company" title="<?= $escaper->escapeHtmlAttr(__('Company')) ?>" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCompany()) ?>" class="input-text <?= $escaper->escapeHtmlAttr($this->helper(Address::class)->getAttributeValidationClass('company')) ?>">
            </div>
        </div>
        <?php $phoneValidation = $this->helper(Address::class)->getAttributeValidationClass('telephone'); ?>
        <div class="field telephone<?php if (strpos($phoneValidation, 'required') !== false): ?> required<?php endif; ?>">
            <label class="label" for="telephone"><span><?= $escaper->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[telephone]" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>" title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text <?= $escaper->escapeHtmlAttr($phoneValidation) ?>" id="telephone">
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset address">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Cardholder Address')) ?></span></legend><br>

        <?php $_streetValidationClass = $escaper->escapeHtmlAttr($this->helper(Address::class)->getAttributeValidationClass('street')); ?>
        <div class="field street required">
            <label for="street" class="label"><span><?= $escaper->escapeHtml(__('Street')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[street][]" value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= $escaper->escapeHtmlAttr(__('Street Address')) ?>" id="street" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>"  />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper(Address::class)->getStreetLines(); $_i < $_n; $_i++): ?>
                        <?php $lineNo = (int)($_i+1); ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */ $lineNo ?>">
                                <span><?= $escaper->escapeHtml(__('Street Address %1', $lineNo)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="billing[street][]" value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($lineNo)) ?>" title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $lineNo)) ?>" id="street_<?= /* @noEscape */ $lineNo ?>" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?= $escaper->escapeHtml(__('City')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[city]" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>" title="<?= $escaper->escapeHtmlAttr(__('City')) ?>" class="input-text <?= $escaper->escapeHtmlAttr($this->helper(Address::class)->getAttributeValidationClass('city')) ?>" id="city">
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region-id"><span><?= $escaper->escapeHtml(__('State/Province')) ?></span></label>
            <div class="control">
                <select id="region-id" name="billing[region_id]" title="<?= $escaper->escapeHtmlAttr(__('State/Province')) ?>" class="validate-select" <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="region" name="billing[region]" value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"  title="<?= $escaper->escapeHtmlAttr(__('State/Province')) ?>" class="input-text <?= $escaper->escapeHtmlAttr($this->helper(Address::class)->getAttributeValidationClass('region')) ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?= $escaper->escapeHtml(__('Zip/Postal Code')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[postcode]" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= $escaper->escapeHtmlAttr(__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?= $escaper->escapeHtmlAttr($this->helper(Address::class)->getAttributeValidationClass('postcode')) ?>">
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?= $escaper->escapeHtml(__('Country')) ?></span></label>
            <div class="control">
                <?= /* @noEscape */ $block->getCountryHtmlSelect($block->getAddress()->getCountryId(), 'billing[country_id]') ?>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar address">
        <div class="primary">
            <button type="button" class="action primary" id="submit-address">
                <span><?= $escaper->escapeHtml(__('Confirm Address')) ?></span>
            </button>
        </div>
    </div>
    <fieldset class="fieldset address">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Payment Information')) ?></span></legend><br>

        <div class="field">
            <p><?= $escaper->escapeHtml(__('Please confirm your address to enter payment info.')) ?></p>
        </div>
    </fieldset>
    <fieldset class="fieldset payment hide-fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Cardholder Information')) ?></span></legend><br>

        <div class="field" id="<?= /* @noEscape */ $code ?>-address">
            <address></address>
            <button type="button" class="action" id="edit-address">
                <span><?= $escaper->escapeHtml(__('Edit')) ?></span>
            </button>
        </div>
    </fieldset>
    <fieldset class="fieldset payment <?= /* @noEscape */ $code ?> hide-fieldset">
        <div class="field required">
            <div class="control">
                <iframe src="about:blank" frameborder="0" id="<?= /* @noEscape */ $code ?>_iframe" name="<?= /* @noEscape */ $code ?>_iframe"></iframe>
            </div>
        </div>
    </fieldset>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {},
            "authnetcimHostedPaymentInfo": {
                "method": "<?= /* @noEscape */ $code ?>",
                "target": "<?= /* @noEscape */ $code ?>_iframe",
                "paramUrl": "<?= $escaper->escapeJs($block->getUrl('authnetcim/hosted/getProfileParams', ['method' => $code])) ?>",
                "updateCardUrl": "<?= $escaper->escapeJs($block->getUrl('authnetcim/hosted/updateCard', ['method' => $code])) ?>",
                "successUrl": "<?= $escaper->escapeJs($block->getUrl('*/*', ['method' => $code])) ?>"
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region-id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int)$block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php $inlineStyle = <<<CSS
    \#{$code}_iframe {
        width: 100%;
        min-width: 300px;
        max-width: 550px;
        height: 400px;
        border: 0;
    }
CSS;
?>
<?php if (isset($secureRenderer) && $secureRenderer instanceof SecureHtmlRenderer): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('style', [], $inlineStyle, false) ?>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag('display:none', '#form-validate .hide-fieldset') ?>
<?php else: ?>
    <style><?= /* @noEscape */ $inlineStyle ?></style>
    <script>
        var elements = document.querySelectorAll('#form-validate .hide-fieldset');
        if (elements) {
            for (var index in elements) {
                elements[el].style.display = 'none';
            }
        }
    </script>
<?php endif; ?>
