<?php
/** @var \ParadoxLabs\Authnetcim\Block\Form\Cc $block */

$code           = $block->escapeHtmlAttr($block->getMethodCode());
$image          = $block->getBrandingImage();
$storedCards    = $block->getStoredCards();
?>
<fieldset class="fieldset payment items ccard <?= /* @noEscape */ $code ?>" id="payment_form_<?= /* @noEscape */ $code ?>">
    <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="source" value="checkout" />

    <?php if ($image): ?>
        <div class="sorter">
            <img src="<?= $block->escapeUrl($image); ?>" />
        </div>
    <?php endif; ?>

    <?php if ($block->haveStoredCards()): ?>
        <div class="field">
            <label for="<?= /* @noEscape */ $code ?>-card-id" class="label"><span><?= $block->escapeHtml(__('Payment Information')) ?></span></label>
            <div class="input-box">
                <select id="<?= /* @noEscape */ $code ?>-card-id" name="payment[card_id]">
                    <?php /** @var \ParadoxLabs\TokenBase\Model\Card $card */ ?>
                    <?php foreach ($storedCards as $card): ?>
                        <?php $card = $card->getTypeInstance(); ?>
                        <option value="<?= $block->escapeHtmlAttr($card->getHash()) ?>" <?php if ($card->getId() == $block->getInfoData('tokenbase_id') || count($storedCards) == 1): ?>selected="selected"<?php endif; ?> data-type="<?= $block->escapeHtmlAttr($card->getType()) ?>">
                            <?= $block->escapeHtml($card->getLabel()) ?>
                        </option>
                    <?php endforeach; ?>
                    <option value=''><?= $block->escapeHtml(__('Add new card')) ?></option>
                </select>
            </div>
        </div>
    <?php endif; ?>

    <div class="field card required hide-if-card-selected">
        <div class="control">
            <iframe src="about:blank" frameborder="0" id="<?= /* @noEscape */ $code ?>_iframe" name="<?= /* @noEscape */ $code ?>_iframe"></iframe>
        </div>
    </div>

    <?php if ($block->hasVerification()): ?>
        <div class="field cvv required <?php if ($block->getMethod()->getConfigData('require_ccv') == 0): ?>hide-if-card-selected<?php endif; ?>">
            <label for="<?= /* @noEscape */ $code ?>-cc-cid" class="label"><span><?= $block->escapeHtml(__('Card Verification Number')) ?></span></label>
            <div class="control _with-tooltip">
                <input type="hidden" name="payment[cc_type]" id="<?= /* @noEscape */ $code ?>-cc-type" value="" />
                <input type="text" title="<?= $block->escapeHtmlAttr(__('Card Verification Number')) ?>" class="input-text cvv" id="<?= /* @noEscape */ $code ?>-cc-cid" name="payment[cc_cid]" value="" data-validate='{"required-number":true, "validate-cc-cvn":"#<?= /* @noEscape */ $code ?>-cc-type"}' autocomplete="cc-csc" maxlength="4" />
                <div class="field-tooltip tooltip note toggle">
                    <span class="field-tooltip-action tooltip-toggle action-cvv" tabindex="0" data-toggle="dropdown">
                        <span><?= $block->escapeHtml(__('What is this?')) ?></span>
                    </span>
                    <div class="tooltip-content" data-target="dropdown" aria-hidden="true">
                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Checkout::cvv.png')) ?>" alt="<?= $block->escapeHtmlAttr(__('Card Verification Number Visual Reference')) ?>" title="<?= $block->escapeHtmlAttr(__('Card Verification Number Visual Reference')) ?>" />
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?= /* @noEscape */ $block->getChildHtml(); ?>
    <?php if (!$block->isGuestCheckout()): ?>
        <div class="field save">
            <div class="control">
                <?php if ($block->getMethod()->getConfigData('allow_unsaved')): ?>
                    <input type="hidden" name="payment[save]" value="0" />
                    <input type="checkbox" title="<?= $block->escapeHtmlAttr(__('Save for next time')) ?>" class="input-checkbox" id="<?= /* @noEscape */ $code ?>_save" name="payment[save]" value="1" <?php if ($block->getMethod()->getConfigData('savecard_opt_out') && $block->getInfoData('save') !== 0): ?>checked="checked"<?php endif; ?> />
                    <label for="<?= /* @noEscape */ $code ?>_save"><?= $block->escapeHtml(__('Save for next time')) ?></label>
                <?php else: ?>
                    <input type="hidden" name="payment[save]" value="1" />
                    <label class="label" for="<?= /* @noEscape */ $code ?>_save"><?= $block->escapeHtml(__('For your convenience, this data will be stored securely by our payment processor.')) ?></label>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
</fieldset>
<script type="text/x-magento-init">
    {
        "#payment_form_<?= /* @noEscape */ $code ?>": {
            "tokenbaseForm": {
                "code": "<?= /* @noEscape */ $code ?>"
            },
            "authnetcimHostedForm": {
                "method": "<?= /* @noEscape */ $code ?>",
                "target": "<?= /* @noEscape */ $code ?>_iframe",
                "paramUrl": "<?= $block->escapeJs($block->getUrl('authnetcim/hosted/getProfileParams', ['source' => 'checkout'])) ?>",
                "newCardUrl": "<?= $block->escapeJs($block->getUrl('authnetcim/hosted/getNewCard')) ?>"
            }
        }
    }
</script>
<?php $inlineStyle = <<<CSS
    \#{$code}_iframe {
        width: 100%;
        min-width: 300px;
        max-width: 550px;
        height: 400px;
        border: 0;
    }
CSS;
?>
<?php if (isset($secureRenderer) && $secureRenderer instanceof \Magento\Framework\View\Helper\SecureHtmlRenderer): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('style', [], $inlineStyle, false) ?>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag('display:none', '#payment_form_' . $code) ?>
<?php else: ?>
    <style><?= /* @noEscape */ $inlineStyle ?></style>
    <script>
        if (document.querySelector('#payment_form_<?= /* @noEscape */ $code ?>') instanceof Element) {
            document.querySelector('#payment_form_<?= /* @noEscape */ $code ?>').style.display = 'none';
        }
    </script>
<?php endif; ?>

