<?php
/** @var \ParadoxLabs\TokenBase\Block\Form\Cc $block */
// @codingStandardsIgnoreFile

$code           = $block->escapeHtmlAttr($block->getMethodCode());
$image          = $block->getBrandingImage();
$storedCards    = $block->getStoredCards();
?>
<div id="payment_form_<?= $code ?>" class="admin__page-section-item checkout-payment-method" style="display:none" data-mage-init='{
    "tokenbaseForm": {
        "code":"<?= $code ?>",
        "validateForm": false
    },
    "tokenbaseCardFormatter": {
        "ccTypeSelector": "#<?= $code ?>-cc-type",
        "ccTypeContainer": ".credit-card-types"
    }
<?php if ($block->getTokenbaseMethod()->isAcceptJsEnabled() === true): ?>,
    "authnetcimAcceptjs": {
        "apiLoginId": "<?= $block->escapeHtmlAttr($block->getMethod()->getConfigData('login')); ?>",
        "clientKey": "<?= $block->escapeHtmlAttr($block->getMethod()->getConfigData('client_key')); ?>",
        "method": "<?= $code; ?>",
        "formSelector": "#edit_form",
        "submitSelector": "#edit_form button.save, #submit_order_top_button",
        "cardSelector": "#<?= $code ?>-card-id",
        "sandbox": <?= $block->getMethod()->getConfigData('test') ? 'true' : 'false'; ?>
    }
<?php endif; ?>
}'>
    <input id="<?= $code ?>-payment-method" type="hidden" name="payment[method]" value="<?= $code ?>" />
    <?php if ($block->getTokenbaseMethod()->isAcceptJsEnabled() === true): ?>
        <input type="hidden" name="payment[acceptjs_key]" id="<?= $code ?>-acceptjs-key" value="" />
        <input type="hidden" name="payment[acceptjs_value]" id="<?= $code ?>-acceptjs-value" value="" />
        <input type="hidden" name="payment[cc_last4]" id="<?= $code ?>-cc-last4" value="" />
        <?php if ($block->getTokenbaseMethod()->getConfigData('can_store_bin') == 1): ?>
            <input type="hidden" name="payment[cc_bin]" id="<?= $code ?>-cc-bin" value="" />
        <?php endif; ?>
    <?php endif; ?>
    <fieldset class="admin__fieldset payment items ccard">
        <?php if ($image): ?>
            <div class="page-actions">
                <img src="<?= $block->escapeUrl($image); ?>" />
            </div>
        <?php endif; ?>
        <?php if ($block->haveStoredCards()): ?>
            <div class="admin__field">
                <div class="admin__field-control control">
                    <select id="<?= $code ?>-card-id" name="payment[card_id]" class="select admin__control-select">
                        <?php /** @var \ParadoxLabs\TokenBase\Model\Card $card */ ?>
                        <?php foreach ($storedCards as $card): ?>
                            <?php $card = $card->getTypeInstance(); ?>
                            <option value="<?= $block->escapeHtmlAttr($card->getHash()) ?>" <?php if ($card->getId() == $block->getInfoData('tokenbase_id') || count($storedCards) == 1): ?>selected="selected"<?php endif; ?> data-type="<?= $block->escapeHtmlAttr($card->getType()) ?>">
                                <?= $block->escapeHtml($card->getLabel()) ?>
                            </option>
                        <?php endforeach; ?>
                        <option value='' <?php if (count($storedCards) > 1 && $block->getInfoData('tokenbase_id') == ''): ?>selected="selected"<?php endif; ?>><?= $block->escapeHtml(__('Add new card')) ?></option>
                    </select>
                </div>
            </div>
        <?php endif; ?>
        <div class="admin__field _required type hide-if-card-selected">
            <div class="admin__field-control control">
                <?php $_ccType = $block->getInfoData('cc_type') ?>
                <ul class="credit-card-types">
                    <?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <li class="item<?php if ($_typeCode == $_ccType): ?> _active<?php endif; ?>" data-type="<?= $block->escapeHtmlAttr($_typeCode); ?>">
                            <img src="<?= $block->getViewFileUrl('Magento_Payment::images/cc/' . strtolower((string)$_typeCode) . '.png'); ?>" alt="<?= $block->escapeHtmlAttr($_typeName); ?>" />
                        </li>
                    <?php endforeach; ?>
                </ul>
                <input type="hidden" name="payment[cc_type]" id="<?= $code ?>-cc-type" value="<?= $block->escapeHtmlAttr($_ccType); ?>" />
            </div>
        </div>
        <div class="admin__field _required number hide-if-card-selected">
            <label class="label admin__field-label" for="<?= $code ?>-cc-number"><span><?= $block->escapeHtml(__('Credit Card Number')) ?></span></label>
            <div class="admin__field-control control">
                <input type="text" id="<?= $code ?>-cc-number" name="payment[cc_number]"  title="<?= $block->escapeHtmlAttr(__('Credit Card Number')) ?>" class="input-text admin__control-text validate-cc-number validate-cc-type" value="<?= $block->escapeHtmlAttr($block->getInfoData('cc_number')); ?>" data-validate='{"required-number":true, "validate-cc-number":"#<?= $code ?>-cc-type", "validate-cc-type":"#<?= $code ?>-cc-type"}' autocomplete="cc-number" />
            </div>
        </div>
        <div class="admin__field _required date hide-if-card-selected">
            <label class="label admin__field-label" for="<?= $code ?>-cc-exp-month"><span><?= $block->escapeHtml(__('Expiration Date')) ?></span></label>
            <div class="admin__field-control control">
                <select id="<?= $code ?>-cc-exp-month" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry _required select admin__control-select" data-validate='{required:true, "validate-cc-exp":"#<?= $code ?>-cc-exp-year"}' autocomplete="cc-exp-month">
                    <?php $_ccExpMonth = $block->getInfoData('cc_exp_month') ?>
                    <?php foreach ($block->getCcMonths() as $k=>$v): ?>
                        <option value="<?= $k?$block->escapeHtmlAttr($k):'' ?>"<?php if ($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?= $block->escapeHtml($v) ?></option>
                    <?php endforeach ?>
                </select>
                <?php $_ccExpYear = $block->getInfoData('cc_exp_year') ?>
                <select id="<?= $code ?>-cc-exp-year" name="payment[cc_exp_year]" class="year required-entry _required select admin__control-select" data-validate='{required:true}' autocomplete="cc-exp-year">
                    <?php foreach ($block->getCcYears() as $k=>$v): ?>
                        <option value="<?= $k?$block->escapeHtmlAttr($k):'' ?>"<?php if ($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?= $block->escapeHtml($v) ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <?= $block->getChildHtml() ?>
        <?php if ($block->hasVerification()): ?>
            <div class="admin__field _required cvv <?php if ($block->getMethod()->getConfigData('require_ccv') == 0): ?>hide-if-card-selected<?php endif; ?>">
                <label class="label admin__field-label" for="<?= $code ?>-cc-cid" ><span><?= $block->escapeHtml(__('Card Verification Number')) ?></span></label>
                <div class="admin__field-control control">
                    <div class="v-fix">
                        <input type="text" title="<?= $block->escapeHtmlAttr(__('Card Verification Number')) ?>" class="input-text admin__control-text cvv required-entry" id="<?= $code ?>-cc-cid" name="payment[cc_cid]" value="<?= $block->escapeHtmlAttr($block->getInfoData('cc_cid')); ?>" data-validate='{"required-number":true}' autocomplete="cc-csc" />
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!$block->isGuestCheckout()): ?>
            <div class="admin__field save hide-if-card-selected">
                <div class="admin__field-control control">
                    <?php if ($block->getMethod()->getConfigData('allow_unsaved')): ?>
                        <input type="hidden" name="payment[save]" value="0" />
                        <input type="checkbox" title="<?= $block->escapeHtmlAttr(__('Save for next time')) ?>" class="input-checkbox" id="<?= $code ?>-save" name="payment[save]" value="1" <?php if ($block->getMethod()->getConfigData('savecard_opt_out') && $block->getInfoData('save') !== 0): ?>checked="checked"<?php endif; ?> />
                        <label for="<?= $code ?>-save"><?= $block->escapeHtml(__('Save for next time')) ?></label>
                    <?php else: ?>
                        <input type="hidden" name="payment[save]" value="1" />
                        <label class="label admin__field-label" for="<?= $code ?>-save"><?= $block->escapeHtml(__('For your convenience, this data will be stored securely by our payment processor.')) ?></label>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </fieldset>
</div>
