<?php
/** @var \ParadoxLabs\TokenBase\Block\Adminhtml\Customer\Form $block */
// @codingStandardsIgnoreFile
?>
<?php $code = $block->escapeHtmlAttr($block->getCode()); ?>

<div class="block-title">
    <h2>
        <?php if ($block->isEdit()): ?>
            <?= $block->escapeHtml(__('Editing %1', $block->getCard()->getLabel())) ?>
        <?php else: ?>
            <?= $block->escapeHtml(__($block->getData('default_title'))) ?>
        <?php endif; ?>
    </h2>
</div>

<form action="<?= $block->escapeHtmlAttr($block->getAction()) ?>" method="post" id="<?= /* @noEscape */ $code ?>-form-validate" class="checkout-payment-method" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{
    "tokenbaseCardFormatter": {
        "ccTypeSelector": "#<?= /* @noEscape */ $code ?>-cc-type",
        "ccTypeContainer": ".credit-card-types"
    },
    "authnetcimHostedPaymentInfo": {
        "method": "<?= /* @noEscape */ $code ?>",
        "target": "<?= /* @noEscape */ $code ?>_iframe",
        "paramUrl": "<?= $block->escapeJs($block->getUrl('authnetcim/hosted/getProfileParams', ['id' => $this->getRequest()->getParam('id'), 'method' => $code])) ?>",
        "updateCardUrl": "<?= $block->escapeJs($block->getUrl('authnetcim/hosted/updateCard', ['id' => $this->getRequest()->getParam('id'), 'method' => $code])) ?>",
        "fieldPrefix": "#<?= /* @noEscape */ $code ?>-"
    }
}'>
    <?= $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="card_id" value="<?= $block->getCard()->getId() ? $block->escapeHtmlAttr($block->getCard()->getHash()) : '' ?>" />
    <input type="hidden" name="method" value="<?= /* @noEscape */ $code ?>" />
    <input type="hidden" name="source" value="paymentinfo" />
    <fieldset class="admin__fieldset address">
        <div class="admin__fieldset-wrapper-title">
            <strong class="title">
                <span><?= $block->escapeHtml(__('Cardholder Information')) ?></span>
            </strong>
        </div>
        <div class="admin__field field-name-firstname _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>-firstname"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[firstname]" id="<?= /* @noEscape */ $code ?>-firstname" title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getFirstname()) ?>" class="admin__control-text input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('firstname')) ?>" data-validate='{required:true}'>
            </div>
        </div>
        <div class="admin__field field-name-lastname _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>-lastname"><span><?= $block->escapeHtml(__('Last Name')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[lastname]" id="<?= /* @noEscape */ $code ?>-lastname" title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getLastname()) ?>" class="admin__control-text input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('lastname')) ?>" data-validate='{required:true}'>
            </div>
        </div>
        <div class="admin__field company">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>-company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[company]" id="<?= /* @noEscape */ $code ?>-company" title="<?= $block->escapeHtmlAttr(__('Company')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCompany()) ?>" class="admin__control-text input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('company')) ?>">
            </div>
        </div>
        <?php $phoneValidation = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('telephone'); ?>
        <div class="admin__field telephone<?php if (strpos((string)$phoneValidation, 'required') !== false): ?> _required<?php endif; ?>">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>-telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[telephone]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="admin__control-text input-text <?= $block->escapeHtmlAttr($phoneValidation) ?>" id="<?= /* @noEscape */ $code ?>-telephone" data-validate='{required:true}'>
            </div>
        </div>
    </fieldset>
    <fieldset class="admin__fieldset address">
        <div class="admin__fieldset-wrapper-title">
            <strong class="title">
                <span><?= $block->escapeHtml(__('Cardholder Address')) ?></span>
            </strong>
        </div>
        <?php $_streetValidationClass = $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street')); ?>
        <div class="admin__field street _required">
            <label for="<?= /* @noEscape */ $code ?>-street" class="admin__field-label"><span><?= $block->escapeHtml(__('Street')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[street][]" value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="<?= /* @noEscape */ $code ?>-street" class="admin__control-text input-text <?= $_streetValidationClass ?>" data-validate='{required:true}' />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php /** NB: Secure Acceptance only supports 2 street lines according to documentation */ ?>
                    <?php for ($_i = 1, $_n = min(2, $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines()); $_i < $_n; $_i++): ?>
                        <?php $lineNo = (int)($_i + 1); ?>
                        <div class="admin__field additional">
                            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>-street_<?= $lineNo ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $lineNo)) ?></span>
                            </label>
                            <div class="admin__field-control">
                                <input type="text" name="billing[street][]" value="<?= $block->escapeHtmlAttr($block->getStreetLine($lineNo)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $lineNo)) ?>" id="<?= /* @noEscape */ $code ?>-street_<?= $lineNo ?>" class="admin__control-text input-text <?= $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
        <div class="admin__field city _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>-city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[city]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="admin__control-text input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="<?= /* @noEscape */ $code ?>-city" data-validate='{required:true}'>
            </div>
        </div>
        <div class="admin__field region _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>-region-id"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
            <div class="admin__field-control">
                <select id="<?= /* @noEscape */ $code ?>-region-id" name="billing[region_id]" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="admin__control-select validate-select" <?=(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="<?= /* @noEscape */ $code ?>-region" name="billing[region]" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="admin__control-text input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>"<?=(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '' ?>/>
            </div>
        </div>
        <div class="admin__field zip _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>-zip"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[postcode]" value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>" id="<?= /* @noEscape */ $code ?>-zip" class="admin__control-text input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
            </div>
        </div>
        <div class="admin__field country _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>-country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="admin__field-control">
                <?= str_replace('class="', 'class="admin__control-select ', $block->getCountryHtmlSelect($block->getAddress()->getCountryId(), 'billing[country_id]', $code . '-country')) ?>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar address">
        <div class="primary">
            <button type="button" class="action primary" id="submit-address">
                <span><?= $block->escapeHtml(__('Confirm Address')) ?></span>
            </button>
        </div>
    </div>
    <fieldset class="admin__fieldset address">
        <div class="admin__fieldset-wrapper-title">
            <strong class="title">
                <span><?= $block->escapeHtml(__('Payment Information')) ?></span>
            </strong>
        </div>

        <div class="admin__field">
            <div class="admin__field-control">
                <p><?= $block->escapeHtml(__('Please confirm your address to enter payment info.')) ?></p>
            </div>
        </div>
    </fieldset>
    <fieldset class="admin__fieldset payment hide-fieldset">
        <div class="admin__fieldset-wrapper-title">
            <strong class="title">
                <span><?= $block->escapeHtml(__('Cardholder Information')) ?></span>
            </strong>
        </div>

        <div class="admin__field-field" id="<?= /* @noEscape */ $code ?>-address">
            <div class="admin__field-control">
                <address></address>
                <button type="button" class="action" id="edit-address">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </button>
            </div>
        </div>
    </fieldset>
    <fieldset class="admin__fieldset payment <?= /* @noEscape */ $code ?> hide-fieldset">
        <div class="admin__field type _required">
            <div class="admin__field-control">
                <iframe src="about:blank" frameborder="0" id="<?= /* @noEscape */ $code ?>_iframe" name="<?= /* @noEscape */ $code ?>_iframe"></iframe>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action-back" href="<?= $block->escapeHtmlAttr($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Cancel')) ?></span></a>
        </div>
    </div>
</form>
<?php $regionId = (int)$block->getRegionId() ?>
<?php /* @see Magento\Customer\Block\Adminhtml\Edit\Renderer\Region::render() */ ?>
<?php $inlineScript = <<<JS
    require(["prototype", "mage/adminhtml/form"], function(){
        jQuery("#{$code}-region-id").attr("defaultValue", "{$regionId}");
        new RegionUpdater("{$code}-country", "{$code}-region", "{$code}-region-id", {$this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson()} );
    });

    require(["jquery"], function() {
        /** This is necessary for parsing of mage-data-init elements in the AJAX requests */
        jQuery('#{$code}-form-validate').trigger('contentUpdated');
    });
JS;
?>
<?php $inlineStyle = <<<CSS
    \#{$code}_iframe {
        width: 100%;
        min-width: 300px;
        max-width: 550px;
        height: 400px;
        border: 0;
    }
CSS;
?>
<?php if (isset($secureRenderer) && $secureRenderer instanceof \Magento\Framework\View\Helper\SecureHtmlRenderer): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $inlineScript, false) ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('style', [], $inlineStyle, false) ?>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag('display:none', '#' . $code . '-form-validate .hide-fieldset') ?>
<?php else: ?>
    <script><?= /* @noEscape */ $inlineScript ?></script>
    <script>
        var elements = document.querySelectorAll('#<?= /* @noEscape */ $code ?>-form-validate .hide-fieldset');
        if (elements) {
            for (var index in elements) {
                elements[el].style.display = 'none';
            }
        }
    </script>
    <style><?= /* @noEscape */ $inlineStyle ?></style>
<?php endif; ?>
