<?php /** @var $block \ParadoxLabs\Authnetcim\Block\Adminhtml\Config\ValidateButton */ ?>
<?php $code = $block->escapeJsQuote($block->getGroupCode()) ?>

<?php $website = (int)$block->getRequest()->getParam('website') ?: 'null' ?>
<?php $store   = (int)$block->getRequest()->getParam('store') ?: 'null' ?>
<?php $inlineScript = <<<JS
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'mage/translate'
    ], function(\$, alert) {
        jQuery('#{$block->escapeJs($block->getButtonId())}').on('click', function() {
            jQuery('#{$block->escapeJs($block->getButtonId())}_results').hide();
            jQuery('body').trigger('processStart');
            jQuery.post({
                url: '{$block->escapeUrl($block->getAjaxUrl())}',
                data: {
                    apiLoginId: jQuery('input[name="groups[{$code}][fields][login][value]"]').val(),
                    transactionKey: jQuery('input[name="groups[{$code}][fields][trans_key][value]"]').val(),
                    signatureKey: jQuery('input[name="groups[{$code}][fields][signature_key][value]"]').val(),
                    sandbox: jQuery('select[name="groups[{$code}][fields][test][value]"]').val(),
                    webhooks: jQuery('select[name="groups[{$code}][fields][webhooks][value]"]').val(),
                    website: {$website},
                    store: {$store}
                },
                dataType: 'json',
                complete: function() {
                    jQuery('body').trigger('processStop');
                },
                success: function(response) {
                    jQuery('#{$block->escapeJs($block->getButtonId())}_results').html(response.message).show();
                },
                error: function(jqXHR, status, error) {
                    var message = jQuery.mage.__('An error occurred. Please try again.');

                    try {
                        var responseJson = JSON.parse(jqXHR.responseText);
                        if (responseJson.message !== undefined) {
                            message = responseJson.message;
                        }
                    } catch (error) {}

                    try {
                        alert({
                            title: jQuery.mage.__('Error'),
                            content: message
                        });
                    } catch (error) {
                        // Fall back to standard alert if jq widget hasn't initialized yet
                        window.alert(message);
                    }
                }
            });
        });
    });
JS;
?>
<?php if (isset($secureRenderer) && $secureRenderer instanceof \Magento\Framework\View\Helper\SecureHtmlRenderer): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $inlineScript, false) ?>
<?php else: ?>
    <script><?= $inlineScript ?></script>
<?php endif; ?>

<?= $block->getButtonHtml() ?>
<div class="testSuccess" id="<?= $block->escapeJs($block->getButtonId()) ?>_results"></div>
