<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <?php $inlineScript = <<<JS
            function communicateAuthnetResponse(message)
            {
                if (message && message.length > 0 && window.parent && window.parent.parent) {
                    window.parent.parent.postMessage(
                        parseQueryString(message),
                        window.self.origin
                    );
                }
            }

            function receiveAuthnetMessage(event)
            {
                if (event && event.data) {
                    if (event.origin === 'https://test.authorize.net'
                        || event.origin === 'https://accept.authorize.net') {
                        communicateAuthnetResponse(event.data);
                    } else {
                        console.error('Ignored untrusted message from ' + event.origin);
                    }
                }
            }

            function parseQueryString(str) {
                var vars = [];
                var arr  = str.split('&');
                var pair;
                for (var i = 0; i < arr.length; i++) {
                    pair = arr[i].split('=');
                    vars.push(pair[0]);
                    vars[pair[0]] = unescape(pair[1]);
                }
                return vars;
            }

            window.addEventListener('message', receiveAuthnetMessage, false);

            if (window.location.hash && window.location.hash.length > 1) {
                communicateAuthnetResponse(window.location.hash.substring(1));
            } else {
                communicateAuthnetResponse('action=ping');
            }
        JS; ?>
        <?php $mockJS = <<<JS
            var \$ = jQuery = req = requirejs = require = depend = function() {
            }
        JS; ?>
        <?php if (isset($secureRenderer) && $secureRenderer instanceof \Magento\Framework\View\Helper\SecureHtmlRenderer): ?>
            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $inlineScript, false) ?>
            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $mockJS, false) ?>
        <?php else: ?>
            <script><?= $inlineScript ?></script>
            <script><?= $mockJS ?></script>
        <?php endif; ?>
    </head>
    <body>
    </body>
</html>
